[package]
name = "il_runtime"
version = "0.1.0"
authors = ["Dear.Va <hbbqsy123@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
num-derive = "0.2"
byteorder = "1.2.7"